name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main repository
        uses: actions/checkout@v4
        with:
          path: lentoleisenfeld.github.io

      - name: Check out LentoDoc repository
        uses: actions/checkout@v4
        with:
          repository: LentoLeisenfeld/LentoDoc
          path: LentoDoc

      - name: Symlink LentoDoc for tsconfig (and debug)
        run: |
          ln -s "$GITHUB_WORKSPACE/LentoDoc" "$GITHUB_WORKSPACE/lentoleisenfeld.github.io/../LentoDoc"
          echo "---- TREE ----"
          tree -L 4 $GITHUB_WORKSPACE
          echo "---- LENTO DOC API ----"
          ls -l $GITHUB_WORKSPACE/LentoDoc/projects/lentodoc/src/public-api.ts
          echo "---- LENTO DOC LINK ----"
          ls -l $GITHUB_WORKSPACE/lentoleisenfeld.github.io/../LentoDoc/projects/lentodoc/src/public-api.ts

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: lentoleisenfeld.github.io

      - name: Build Angular app
        run: |
          echo "---- DEBUG: tsconfig used ----"
          cat tsconfig.json
          cat tsconfig.app.json || true
          echo "---- END DEBUG ----"
          npx ng build --base-href /
        working-directory: lentoleisenfeld.github.io

      - name: Add CNAME for custom domain
        run: echo 'leisenfeld.com' > dist/website/browser/CNAME
        working-directory: lentoleisenfeld.github.io

      - name: Copy index.html to 404.html for Angular SPA fallback
        run: cp dist/website/browser/index.html dist/website/browser/404.html
        working-directory: lentoleisenfeld.github.io

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lentoleisenfeld.github.io/dist/website/browser
